In [24]:
import os, datetime
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as colors

from tensorflow import keras
from utils.miscellaneous import create_seq_dataset_multiple_input_single_output
from utils.layer import FeatureWiseScalingLayer, DecompositionLayer
from utils.assemble_model import build_reg_model
from matplotlib.ticker import MultipleLocator, FuncFormatter


print("TensorFlow version:", tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("Available GPUs:", tf.config.list_physical_devices('GPU'))

TensorFlow version: 2.10.0
Num GPUs Available: 1
Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [25]:
feature_name_list = ['inlet_pressure(bar)', 'outlet_pressure(bar)', 'pump_speed(rpm)']
target_name = 'outlet_flowrate(lpm)'

file_name_list = os.listdir(os.path.join('data', 'train_data'))
data_list = []

for file_name in file_name_list:
    file_path = os.path.join('data', 'train_data', file_name)
    data = pd.read_csv(file_path)
    data.columns = ['time(sec)'] + feature_name_list + [target_name]

    max_time = np.round(data['time(sec)'].max(), 0)
    time_ref_arr = np.arange(0, max_time, 0.5)
    sorted_data = []

    for ref_time in time_ref_arr:
        idx = np.argmin(np.abs(data['time(sec)'].to_numpy() - ref_time))
        sorted_data.append(data.iloc[idx, :])

    sorted_data = pd.DataFrame(sorted_data)
    sorted_data.reset_index(drop=True, inplace=True)
    data_list.append(data)

train_data = pd.concat(data_list, axis=0)
train_data.shape

(16375, 5)

In [26]:
train_data

,time(sec),inlet_pressure(bar),outlet_pressure(bar),pump_speed(rpm),outlet_flowrate(lpm)
0,0.143,-0.129,-0.114,1,0.000
1,0.256,-0.129,-0.116,1,0.000
2,0.382,-0.129,-0.122,1,0.000
3,0.507,-0.128,-0.107,1,0.000
4,0.622,-0.129,-0.101,1,0.000
...,...,...,...,...,...
2814,367.272,-0.155,0.078,3,262.719
2815,367.404,-0.155,0.060,3,279.999
2816,367.576,-0.156,0.069,3,279.999
2817,367.704,-0.155,0.060,3,279.999
2818,367.836,-0.155,0.064,3,279.999

In [27]:
train_dataset = train_data.copy()
train_dataset = train_dataset[train_dataset[feature_name_list[2]] > 700]
train_dataset = train_dataset[train_dataset[target_name] > 100]
train_dataset.reset_index(drop=True, inplace=True)

train_dataset = train_dataset[feature_name_list+[target_name]].to_numpy()
train_dataset.shape

(13784, 4)

In [28]:
data = pd.read_csv('data/test_data/data20251114-170633.csv')
val_dataset = data.iloc[:, 2:6]
val_dataset.columns = feature_name_list + [target_name]
val_dataset

,inlet_pressure(bar),outlet_pressure(bar),pump_speed(rpm),outlet_flowrate(lpm)
0,0.000,0.000,0.0,0.000
1,0.000,0.000,0.0,0.000
2,-0.169,0.087,1.0,0.000
3,-0.169,0.087,1.0,0.000
4,-0.169,0.087,1.0,0.000
...,...,...,...,...
1782,-0.134,0.109,40.0,9113.203
1783,-0.059,0.032,28.0,9113.203
1784,-0.059,0.032,28.0,9113.203
1785,-0.059,0.032,28.0,9113.203
1786,-0.131,0.096,22.0,7609.335

In [29]:
val_dataset = val_dataset[val_dataset[feature_name_list[2]] > 700]
val_dataset = val_dataset[val_dataset[target_name] > 100]
val_dataset.reset_index(drop=True, inplace=True)

val_dataset = val_dataset.to_numpy()
val_dataset.shape

(1623, 4)

In [30]:
total_dataset = np.concatenate([train_dataset, val_dataset], axis=0)

In [31]:
n_samples = 2000
max_len = 100

random_start_idx = np.random.randint(low=0, high=total_dataset.shape[0]-max_len, size=n_samples)
random_len_idx = np.random.randint(low=20, high=max_len+1, size=n_samples)

buf_2 = np.empty(shape=(0, total_dataset.shape[1]))

for i, j in zip(random_start_idx, random_len_idx):
    buf_2 = np.concatenate([buf_2, total_dataset[i:i+j, :]*0.95], axis=0)


random_start_idx = np.random.randint(low=0, high=total_dataset.shape[0]-max_len, size=n_samples)
random_len_idx = np.random.randint(low=20, high=max_len+1, size=n_samples)

buf_3 = np.empty(shape=(0, total_dataset.shape[1]))

for i, j in zip(random_start_idx, random_len_idx):
    buf_3 = np.concatenate([buf_3, total_dataset[i:i+j, :]*1.05], axis=0)


augment_dataset = np.concatenate([buf_2, buf_3], axis=0)

print(augment_dataset.shape)
print((augment_dataset.itemsize * augment_dataset.size)/(1024**2))

(239544, 4)
7.310302734375

In [32]:
seq_len = 20

train_feature, train_target = create_seq_dataset_multiple_input_single_output(data=augment_dataset, seq_len=seq_len,pred_distance=0,
                                                                              target_idx_pos=augment_dataset.shape[1]-1)
val_feature, val_target = create_seq_dataset_multiple_input_single_output(data=total_dataset, seq_len=seq_len, pred_distance=0,
                                                                          target_idx_pos=total_dataset.shape[1]-1)

train_target = np.squeeze(train_target)
val_target = np.squeeze(val_target)

print(train_feature.shape, train_target.shape)
print(val_feature.shape, val_target.shape)

print((train_feature.itemsize * train_feature.size)/(1024**2))
print((train_target.itemsize * train_target.size)/(1024**2))

creating sequence dataset...:   0%|          | 0/239544 [00:00<?, ?it/s]

creating sequence dataset...:   0%|          | 0/15407 [00:00<?, ?it/s]

(239525, 20, 3) (239525,)
(15388, 20, 3) (15388,)
109.64584350585938
1.8274307250976562

In [33]:
model = build_reg_model(input_shape=(train_feature.shape[1:]), d_dims=128, dropout_rate=0.5, learning_rate=0.001)

model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_2 (InputLayer)           [(None, 20, 3)]      0           []

 tf.__operators__.getitem_2 (Sl  (None, 20, 2)       0           ['input_2[0][0]']
 icingOpLambda)

 tf.__operators__.getitem_3 (Sl  (None, 20, 1)       0           ['input_2[0][0]']
 icingOpLambda)

 batch_normalization_6 (BatchNo  (None, 20, 2)       8           ['tf.__operators__.getitem_2[0][0
 rmalization)                                                    ]']

 layer_normalization_2 (LayerNo  (None, 20, 1)       2           ['tf.__operators__.getitem_3[0][0
 rmalization)                                                    ]']

 concatenate_1 (Concatenate)    (None, 20, 3)        0           ['batch_normalization_6[0][0]',
                                                                  'layer_normalization_2[0][0]']

 dense_2 (Dense)                (None, 20, 128)      512         ['concatenate_1[0][0]']

 conv1d_10 (Conv1D)             (None, 20, 128)      49280       ['dense_2[0][0]']

 dropout_6 (Dropout)            (None, 20, 128)      0           ['conv1d_10[0][0]']

 conv1d_11 (Conv1D)             (None, 20, 128)      49280       ['dropout_6[0][0]']

 tf.__operators__.add_5 (TFOpLa  (None, 20, 128)     0           ['conv1d_11[0][0]',
 mbda)                                                            'dense_2[0][0]']

 batch_normalization_7 (BatchNo  (None, 20, 128)     512         ['tf.__operators__.add_5[0][0]']
 rmalization)

 activation_6 (Activation)      (None, 20, 128)      0           ['batch_normalization_7[0][0]']

 conv1d_12 (Conv1D)             (None, 20, 128)      49280       ['activation_6[0][0]']

 dropout_7 (Dropout)            (None, 20, 128)      0           ['conv1d_12[0][0]']

 conv1d_13 (Conv1D)             (None, 20, 128)      49280       ['dropout_7[0][0]']

 tf.__operators__.add_6 (TFOpLa  (None, 20, 128)     0           ['conv1d_13[0][0]',
 mbda)                                                            'activation_6[0][0]']

 batch_normalization_8 (BatchNo  (None, 20, 128)     512         ['tf.__operators__.add_6[0][0]']
 rmalization)

 activation_7 (Activation)      (None, 20, 128)      0           ['batch_normalization_8[0][0]']

 conv1d_14 (Conv1D)             (None, 20, 128)      49280       ['activation_7[0][0]']

 dropout_8 (Dropout)            (None, 20, 128)      0           ['conv1d_14[0][0]']

 conv1d_15 (Conv1D)             (None, 20, 128)      49280       ['dropout_8[0][0]']

 tf.__operators__.add_7 (TFOpLa  (None, 20, 128)     0           ['conv1d_15[0][0]',
 mbda)                                                            'activation_7[0][0]']

 batch_normalization_9 (BatchNo  (None, 20, 128)     512         ['tf.__operators__.add_7[0][0]']
 rmalization)

 activation_8 (Activation)      (None, 20, 128)      0           ['batch_normalization_9[0][0]']

 conv1d_16 (Conv1D)             (None, 20, 128)      49280       ['activation_8[0][0]']

 dropout_9 (Dropout)            (None, 20, 128)      0           ['conv1d_16[0][0]']

 conv1d_17 (Conv1D)             (None, 20, 128)      49280       ['dropout_9[0][0]']

 tf.__operators__.add_8 (TFOpLa  (None, 20, 128)     0           ['conv1d_17[0][0]',
 mbda)                                                            'activation_8[0][0]']

 batch_normalization_10 (BatchN  (None, 20, 128)     512         ['tf.__operators__.add_8[0][0]']
 ormalization)

 activation_9 (Activation)      (None, 20, 128)      0           ['batch_normalization_10[0][0]']

 conv1d_18 (Conv1D)             (None, 20, 128)      49280       ['activation_9[0][0]']

 dropout_10 (Dropout)           (None, 20, 128)      0           ['conv1d_18[0][0]']

 conv1d_19 (Conv1D)             (None, 20, 128)      49280       ['dropout_10[0][0]']

 tf.__operators__.add_9 (TFOpLa  (None, 20, 128)     0           ['conv1d_19[0][0]',
 mbda)                                                            'activation_9[0][0]']

 batch_normalization_11 (BatchN  (None, 20, 128)     512         ['tf.__operators__.add_9[0][0]']
 ormalization)

 activation_10 (Activation)     (None, 20, 128)      0           ['batch_normalization_11[0][0]']

 flatten_1 (Flatten)            (None, 2560)         0           ['activation_10[0][0]']

 layer_normalization_3 (LayerNo  (None, 2560)        5120        ['flatten_1[0][0]']
 rmalization)

 dropout_11 (Dropout)           (None, 2560)         0           ['layer_normalization_3[0][0]']

 feature_wise_scaling_layer_1 (  (None, 2560)        2560        ['dropout_11[0][0]']
 FeatureWiseScalingLayer)

 dense_3 (Dense)                (None, 1)            2561        ['feature_wise_scaling_layer_1[0]
                                                                 [0]']

==================================================================================================
Total params: 506,123
Trainable params: 504,839
Non-trainable params: 1,284
__________________________________________________________________________________________________

In [ ]:
# keras.utils.plot_model(model, show_shapes=True, show_layer_names=True, show_layer_activations=True, show_dtype=True)

In [34]:
total_params = model.count_params()
trainable_params = np.sum([np.prod(v.shape) for v in model.trainable_weights])
non_trainable_params = np.sum([np.prod(v.shape) for v in model.non_trainable_weights])

print("--- 모델 파라미터 요약 ---")
print(f"Total params: {total_params:,}")
print(f"Trainable params: {int(trainable_params):,}")
print(f"Non-trainable params: {int(non_trainable_params):,}")

--- 모델 파라미터 요약 ---
Total params: 506,123
Trainable params: 504,839
Non-trainable params: 1,284

In [35]:
bytes_per_param_float32 = 4
total_bytes = total_params * bytes_per_param_float32

total_kb = total_bytes / 1024
total_mb = total_kb / 1024

print(f"--- 32비트 (float32) 기준 계산 ---")
print(f"총 파라미터 수: {total_params:,}")
print(f"총 용량 (MB): {total_mb:.2f} MB")

--- 32비트 (float32) 기준 계산 ---
총 파라미터 수: 506,123
총 용량 (MB): 1.93 MB

In [ ]:
log_dir = "logs/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stop = keras.callbacks.EarlyStopping(monitor=f'val_loss', patience=500, verbose=0)
csv_logger = keras.callbacks.CSVLogger(f'result/log_{seq_len}.csv', append=False, separator=',')
model_chk_point = keras.callbacks.ModelCheckpoint(filepath=f'models/model_{seq_len}.keras', monitor="val_loss", verbose=2, save_best_only=True,
                                                  save_weights_only=False, mode="min", save_freq="epoch", initial_value_threshold=None)

model.fit(x=train_feature, y=train_target, validation_data=(val_feature, val_target), epochs=999999,
          batch_size=10000, verbose=0, callbacks=[early_stop, csv_logger, model_chk_point, tensorboard_callback])

In [ ]:
model = keras.models.load_model(f'models/model_{seq_len}.keras', custom_objects={'FeatureWiseScalingLayer': FeatureWiseScalingLayer,
                                                                                 'DecompositionLayer': DecompositionLayer})

In [ ]:
train_result = pd.read_csv(f'result/log_{seq_len}.csv')

loss_df = train_result['loss']
val_loss_df = train_result['val_loss']
mean_abs_loss_df = train_result['mean_absolute_error']
val_mean_abs_loss_df = train_result['val_mean_absolute_error']
mean_abs_per_loss_df = train_result['mean_absolute_percentage_error']
val_mean_abs_per_loss_df = train_result['val_mean_absolute_percentage_error']

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

ax_1 = sns.lineplot(x=np.arange(0, len(loss_df)), y=loss_df, label='Train Loss', color='red')
sns.lineplot(x=np.arange(0, len(val_loss_df)), y=val_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.yscale('log')

plt.ylim(100, 20000)
plt.grid(True, which='minor', linestyle='--', linewidth=1.0)

formatter = FuncFormatter(lambda y, pos: f'{y:.0f}')
ax_1.yaxis.set_major_formatter(formatter)

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

ax1 = sns.lineplot(x=np.arange(0, len(mean_abs_loss_df)), y=mean_abs_loss_df, label='Train Loss', color='red')
ax2 = sns.lineplot(x=np.arange(0, len(val_mean_abs_loss_df)), y=val_mean_abs_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')
plt.ylabel('Mean Absolute Error(LPM)')

#plt.ylim(0, 1000)

for axis in [ax1, ax2]:
    axis.yaxis.set_major_locator(MultipleLocator(100))

plt.ylim(100, 20000)

plt.yscale('log')

formatter = FuncFormatter(lambda y, pos: f'{y:.0f}')
ax1.yaxis.set_major_formatter(formatter)

In [ ]:
sns.set_theme(font_scale=1.2)
sns.set_style('whitegrid', {'grid.linestyle': '--'})

ax1 = sns.lineplot(x=np.arange(0, len(mean_abs_per_loss_df)), y=mean_abs_per_loss_df, label='Train Loss', color='red')
ax2 = sns.lineplot(x=np.arange(0, len(val_mean_abs_per_loss_df)), y=val_mean_abs_per_loss_df, label='Validation Loss', color='green')

plt.xlabel('Epoch')

#plt.yscale('log')
#plt.ylim(10, 100)
plt.ylabel('Relative Error(%)')

formatter = FuncFormatter(lambda y, pos: f'{y:.0f}')
ax1.yaxis.set_major_formatter(formatter)

In [ ]:
fig, ax1 = plt.subplots()

ax1 = sns.lineplot(x=val_loss_df, y=val_mean_abs_loss_df, ax=ax1, color='red')

ax1.set_xscale('log')
ax1.set_xlim(100, 20000)
ax1.set_xlabel('Loss')

#ax1.set_yscale('log')
#ax1.set_ylim(0, 1000)
#ax1.yaxis.set_major_locator(MultipleLocator(2000))
ax1.set_ylabel('Absolute Error(LPM)')

ax2 = ax1.twinx()

sns.lineplot(x=val_loss_df, y=val_mean_abs_per_loss_df, ax=ax2, color='green')

#ax2.set_yscale('log')
#ax2.set_ylim(500, 20000)
ax2.set_ylabel('Relative Error(%)')


line1, = ax1.lines
line2, = ax2.lines

ax1.legend([line1, line2], ['Absolute Error', 'Relative Error'], loc='upper left')

formatter = FuncFormatter(lambda y, pos: f'{y:.0f}')
ax1.xaxis.set_major_formatter(formatter)